### PR TITLE
Add default middleware / trait

### PR DESCRIPTION
**Pull request by RomainLanz**
Hey! 👋 

This PR add some middleware and traits by default.

**Middleware**:

- `AllowGuestOnly` throws an exception if you are authenticated.
- `ConvertEmptyStringsToNull` converts empty strings in the request body to `null`

**Trait**:

- `NoTimestamp` removes the need for `created_at` and `updated_at` fields.
- `FormatDate` formats the date following a convention.

**FormatDate**

The convention is:
- Ends with `_at` => DateTime
- Ends with `_on` => Date

You can change the format you use in your UI with two getters.

```js
class MyModel extends Model {
  static get formatDate () { return 'DD.MM.YYYY' }
  static get formatDateTime () { return 'DD.MM.YYYY HH:mm' }
}
```

You can also directly change default values inside the Trait since it is a user Trait and not defined in the core.

<hr>

If this is merged, I'll provide the same PR to the `API` blueprint.

### CODE REVIEW

**Comment by RomainLanz** [comment]
Also, I'm working on another Trait to provide easy date management from this tips https://twitter.com/romainlanz/status/1042322229109907456.

**Comment by thetutlage** [comment]
Can we have a PR for the docs too? Otherwise we will always miss them :)

**Comment by thetutlage** [comment]
There's a conflict in `package.json` and also I am not sure, if everyone really needs `FormatDate` trait.

I have seen only fraction of people asking to modify the format of dates and expecting this is going to be the right format for them is not the correct assumption. I think, sharing it via recipes is fine

**Comment by RomainLanz** [comment]
Okay, then let's keep only the `ConvertEmptyStringsToNull` middleware and `NoTimestamp` Trait.

**Comment by lffg** [comment]
We can also trim the strings?:

```javascript
if (Object.keys(request.body).length) {
  request.body = Object.assign(
    ...Object.keys(request.body).map((key) => ({
      [key]: request.body[key] !== '' ? (
        typeof request.body[key] === 'string' ? request.body[key].trim() : request.body[key]
      ) : null
    }))
  )
}
```

**Pull request merged**
